// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWHLnBp6RqUdeIKV4CecFrY7AR5cUsJ58',
    appId: '1:740383319474:web:bd77564cdaffc8ed22b0ab',
    messagingSenderId: '740383319474',
    projectId: 'ai-story-gen-55fa9',
    authDomain: 'ai-story-gen-55fa9.firebaseapp.com',
    storageBucket: 'ai-story-gen-55fa9.firebasestorage.app',
    measurementId: 'G-YE336LFELL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH1KeBG7X_aEpJ7Xt076TjeF8WYc6ecIg',
    appId: '1:740383319474:android:502243505f42e7e522b0ab',
    messagingSenderId: '740383319474',
    projectId: 'ai-story-gen-55fa9',
    storageBucket: 'ai-story-gen-55fa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjm3snU21Kc7SfHxUh8iPIeUNaD1hvZAs',
    appId: '1:740383319474:ios:11faa6a027a7f01b22b0ab',
    messagingSenderId: '740383319474',
    projectId: 'ai-story-gen-55fa9',
    storageBucket: 'ai-story-gen-55fa9.firebasestorage.app',
    iosBundleId: 'com.example.aiStoryGen',
  );
}
