name: ai_story_gen
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # for .env file data
  flutter_dotenv: ^5.2.1

  # firebae related depen.
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.2

  # google api 
  google_generative_ai: ^0.4.6

  #
  flutter_tts: ^4.2.0
  shared_preferences: ^2.4.0
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.3

  #state management  
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  pdf: ^3.11.2
  path_provider: ^2.1.5
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icon/
  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
