name: ai_story_gen
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_generative_ai: ^0.4.6
  flutter_tts: ^4.2.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  flutter_native_splash: ^2.4.3
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
  # fonts:
  #   - family: SocialIcons
  #     fonts:
  #       - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
